import { useState, useEffect, useMemo } from "react";
import type { Appointment, AppointmentFilters, Patient } from "../types";
import { mockDoctors } from "./useDoctors";
import { mockSpecialties } from "./useSpecialties";

function getRelativeDate(daysOffset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString().split("T")[0];
}

export const mockPatients: Patient[] = [
  {
    id: "pat-1",
    first_name: "Juan",
    second_name: "Carlos",
    first_lastname: "Pérez",
    second_lastname: "García",
    ci: "V-12345678",
    email: "juan.perez@email.com",
    cellphone: "0414-1234567",
    role: "worker",
    status: "active",
    nhm: "00.00.01",
    initials: "JP",
  },
  {
    id: "pat-2",
    first_name: "María",
    first_lastname: "Fernández",
    second_lastname: "López",
    ci: "V-23456789",
    email: "maria.fernandez@email.com",
    cellphone: "0424-2345678",
    role: "professor",
    status: "active",
    nhm: "00.00.02",
    initials: "MF",
  },
  {
    id: "pat-3",
    first_name: "Andrés",
    first_lastname: "Silva",
    ci: "V-34567890",
    email: "andres.silva@email.com",
    cellphone: "0412-3456789",
    role: "student",
    status: "active",
    nhm: "00.00.03",
    initials: "AS",
  },
  {
    id: "pat-4",
    first_name: "Luisa",
    second_name: "Elena",
    first_lastname: "Torres",
    second_lastname: "Mendoza",
    ci: "V-45678901",
    email: "luisa.torres@email.com",
    cellphone: "0416-4567890",
    role: "family_member",
    status: "active",
    nhm: "00.00.04",
    initials: "LT",
  },
  {
    id: "pat-5",
    first_name: "Pedro",
    first_lastname: "Ramírez",
    ci: "V-56789012",
    email: "pedro.ramirez@email.com",
    cellphone: "0426-5678901",
    role: "worker",
    status: "active",
    nhm: "00.00.05",
    initials: "PR",
  },
  {
    id: "pat-6",
    first_name: "Carolina",
    first_lastname: "Morales",
    second_lastname: "Díaz",
    ci: "V-67890123",
    email: "carolina.morales@email.com",
    cellphone: "0414-6789012",
    role: "student",
    status: "active",
    nhm: "00.00.06",
    initials: "CM",
  },
  {
    id: "pat-7",
    first_name: "Roberto",
    second_name: "José",
    first_lastname: "Castillo",
    ci: "V-78901234",
    email: "roberto.castillo@email.com",
    cellphone: "0424-7890123",
    role: "professor",
    status: "active",
    nhm: "00.00.07",
    initials: "RC",
  },
  {
    id: "pat-8",
    first_name: "Daniela",
    first_lastname: "Vargas",
    second_lastname: "Herrera",
    ci: "V-89012345",
    email: "daniela.vargas@email.com",
    cellphone: "0412-8901234",
    role: "worker",
    status: "active",
    nhm: "00.00.08",
    initials: "DV",
  },
  {
    id: "pat-9",
    first_name: "Gabriel",
    first_lastname: "Mendoza",
    ci: "V-90123456",
    email: "gabriel.mendoza@email.com",
    cellphone: "0416-9012345",
    role: "family_member",
    status: "active",
    nhm: "00.00.09",
    initials: "GM",
  },
  {
    id: "pat-10",
    first_name: "Valentina",
    first_lastname: "Rojas",
    second_lastname: "Paredes",
    ci: "V-01234567",
    email: "valentina.rojas@email.com",
    cellphone: "0426-0123456",
    role: "student",
    status: "active",
    nhm: "00.00.10",
    initials: "VR",
  },
];

const today = getRelativeDate(0);

export const mockAppointments: Appointment[] = [
  // Today's appointments
  {
    id: "apt-001",
    patient_id: "pat-1",
    patient: mockPatients[0],
    doctor_id: "doc-1",
    doctor: mockDoctors[0],
    specialty_id: "sp-1",
    specialty: mockSpecialties[0],
    appointment_type: "first_visit",
    status: "completed",
    scheduled_date: today,
    scheduled_start_time: "08:00",
    scheduled_end_time: "09:00",
    reason: "Dolor en el pecho, evaluación inicial",
    created_at: getRelativeDate(-3),
  },
  {
    id: "apt-002",
    patient_id: "pat-2",
    patient: mockPatients[1],
    doctor_id: "doc-1",
    doctor: mockDoctors[0],
    specialty_id: "sp-1",
    specialty: mockSpecialties[0],
    appointment_type: "follow_up",
    status: "in_progress",
    scheduled_date: today,
    scheduled_start_time: "09:30",
    scheduled_end_time: "10:00",
    reason: "Control de hipertensión",
    created_at: getRelativeDate(-5),
  },
  {
    id: "apt-003",
    patient_id: "pat-3",
    patient: mockPatients[2],
    doctor_id: "doc-2",
    doctor: mockDoctors[1],
    specialty_id: "sp-2",
    specialty: mockSpecialties[1],
    appointment_type: "first_visit",
    status: "confirmed",
    scheduled_date: today,
    scheduled_start_time: "10:00",
    scheduled_end_time: "10:45",
    reason: "Consulta general, malestar estomacal",
    created_at: getRelativeDate(-2),
  },
  {
    id: "apt-004",
    patient_id: "pat-4",
    patient: mockPatients[3],
    doctor_id: "doc-3",
    doctor: mockDoctors[2],
    specialty_id: "sp-3",
    specialty: mockSpecialties[2],
    appointment_type: "follow_up",
    status: "confirmed",
    scheduled_date: today,
    scheduled_start_time: "11:00",
    scheduled_end_time: "11:30",
    reason: "Control dermatitis",
    created_at: getRelativeDate(-4),
  },
  {
    id: "apt-005",
    patient_id: "pat-5",
    patient: mockPatients[4],
    doctor_id: "doc-4",
    doctor: mockDoctors[3],
    specialty_id: "sp-4",
    specialty: mockSpecialties[3],
    appointment_type: "first_visit",
    status: "requested",
    scheduled_date: today,
    scheduled_start_time: "14:00",
    scheduled_end_time: "15:00",
    reason: "Evaluación psicológica inicial",
    created_at: getRelativeDate(-1),
  },
  {
    id: "apt-006",
    patient_id: "pat-6",
    patient: mockPatients[5],
    doctor_id: "doc-5",
    doctor: mockDoctors[4],
    specialty_id: "sp-5",
    specialty: mockSpecialties[4],
    appointment_type: "first_visit",
    status: "confirmed",
    scheduled_date: today,
    scheduled_start_time: "15:00",
    scheduled_end_time: "15:40",
    reason: "Problemas de visión",
    created_at: getRelativeDate(-2),
  },
  // Yesterday
  {
    id: "apt-007",
    patient_id: "pat-7",
    patient: mockPatients[6],
    doctor_id: "doc-1",
    doctor: mockDoctors[0],
    specialty_id: "sp-1",
    specialty: mockSpecialties[0],
    appointment_type: "follow_up",
    status: "completed",
    scheduled_date: getRelativeDate(-1),
    scheduled_start_time: "08:00",
    scheduled_end_time: "08:30",
    reason: "Control post-operatorio cardíaco",
    created_at: getRelativeDate(-7),
  },
  {
    id: "apt-008",
    patient_id: "pat-8",
    patient: mockPatients[7],
    doctor_id: "doc-2",
    doctor: mockDoctors[1],
    specialty_id: "sp-2",
    specialty: mockSpecialties[1],
    appointment_type: "first_visit",
    status: "no_show",
    scheduled_date: getRelativeDate(-1),
    scheduled_start_time: "10:00",
    scheduled_end_time: "10:45",
    reason: "Consulta general",
    created_at: getRelativeDate(-5),
  },
  // Tomorrow
  {
    id: "apt-009",
    patient_id: "pat-9",
    patient: mockPatients[8],
    doctor_id: "doc-3",
    doctor: mockDoctors[2],
    specialty_id: "sp-3",
    specialty: mockSpecialties[2],
    appointment_type: "first_visit",
    status: "confirmed",
    scheduled_date: getRelativeDate(1),
    scheduled_start_time: "09:00",
    scheduled_end_time: "09:45",
    reason: "Evaluación dermatológica, manchas en la piel",
    created_at: getRelativeDate(-3),
  },
  {
    id: "apt-010",
    patient_id: "pat-10",
    patient: mockPatients[9],
    doctor_id: "doc-4",
    doctor: mockDoctors[3],
    specialty_id: "sp-4",
    specialty: mockSpecialties[3],
    appointment_type: "follow_up",
    status: "confirmed",
    scheduled_date: getRelativeDate(1),
    scheduled_start_time: "10:00",
    scheduled_end_time: "10:45",
    reason: "Seguimiento terapia",
    created_at: getRelativeDate(-6),
  },
  {
    id: "apt-011",
    patient_id: "pat-1",
    patient: mockPatients[0],
    doctor_id: "doc-5",
    doctor: mockDoctors[4],
    specialty_id: "sp-5",
    specialty: mockSpecialties[4],
    appointment_type: "first_visit",
    status: "requested",
    scheduled_date: getRelativeDate(1),
    scheduled_start_time: "14:00",
    scheduled_end_time: "14:40",
    reason: "Revisión de agudeza visual",
    created_at: getRelativeDate(0),
  },
  // Day after tomorrow
  {
    id: "apt-012",
    patient_id: "pat-2",
    patient: mockPatients[1],
    doctor_id: "doc-1",
    doctor: mockDoctors[0],
    specialty_id: "sp-1",
    specialty: mockSpecialties[0],
    appointment_type: "follow_up",
    status: "confirmed",
    scheduled_date: getRelativeDate(2),
    scheduled_start_time: "08:30",
    scheduled_end_time: "09:00",
    reason: "Control de presión arterial",
    created_at: getRelativeDate(-2),
  },
  {
    id: "apt-013",
    patient_id: "pat-3",
    patient: mockPatients[2],
    doctor_id: "doc-6",
    doctor: mockDoctors[5],
    specialty_id: "sp-2",
    specialty: mockSpecialties[1],
    appointment_type: "first_visit",
    status: "requested",
    scheduled_date: getRelativeDate(2),
    scheduled_start_time: "11:00",
    scheduled_end_time: "11:45",
    reason: "Dolor de cabeza recurrente",
    created_at: getRelativeDate(0),
  },
  // 3 days from now
  {
    id: "apt-014",
    patient_id: "pat-4",
    patient: mockPatients[3],
    doctor_id: "doc-2",
    doctor: mockDoctors[1],
    specialty_id: "sp-2",
    specialty: mockSpecialties[1],
    appointment_type: "follow_up",
    status: "confirmed",
    scheduled_date: getRelativeDate(3),
    scheduled_start_time: "09:00",
    scheduled_end_time: "09:20",
    reason: "Control medicación",
    created_at: getRelativeDate(-1),
  },
  {
    id: "apt-015",
    patient_id: "pat-5",
    patient: mockPatients[4],
    doctor_id: "doc-3",
    doctor: mockDoctors[2],
    specialty_id: "sp-3",
    specialty: mockSpecialties[2],
    appointment_type: "follow_up",
    status: "confirmed",
    scheduled_date: getRelativeDate(3),
    scheduled_start_time: "10:00",
    scheduled_end_time: "10:30",
    reason: "Seguimiento tratamiento acné",
    created_at: getRelativeDate(-3),
  },
  // 4 days from now
  {
    id: "apt-016",
    patient_id: "pat-6",
    patient: mockPatients[5],
    doctor_id: "doc-1",
    doctor: mockDoctors[0],
    specialty_id: "sp-1",
    specialty: mockSpecialties[0],
    appointment_type: "first_visit",
    status: "requested",
    scheduled_date: getRelativeDate(4),
    scheduled_start_time: "08:00",
    scheduled_end_time: "09:00",
    reason: "Evaluación cardiovascular preventiva",
    created_at: getRelativeDate(0),
  },
  // Cancelled & rescheduled examples
  {
    id: "apt-017",
    patient_id: "pat-7",
    patient: mockPatients[6],
    doctor_id: "doc-4",
    doctor: mockDoctors[3],
    specialty_id: "sp-4",
    specialty: mockSpecialties[3],
    appointment_type: "first_visit",
    status: "cancelled",
    scheduled_date: getRelativeDate(-2),
    scheduled_start_time: "14:00",
    scheduled_end_time: "15:00",
    reason: "Evaluación psicológica",
    cancellation_reason: "Paciente solicitó cancelación por viaje",
    created_at: getRelativeDate(-8),
  },
  {
    id: "apt-018",
    patient_id: "pat-8",
    patient: mockPatients[7],
    doctor_id: "doc-5",
    doctor: mockDoctors[4],
    specialty_id: "sp-5",
    specialty: mockSpecialties[4],
    appointment_type: "follow_up",
    status: "rescheduled",
    scheduled_date: getRelativeDate(-1),
    scheduled_start_time: "15:00",
    scheduled_end_time: "15:20",
    reason: "Control oftalmológico",
    rescheduled_from_id: "apt-old-1",
    created_at: getRelativeDate(-4),
  },
  // 5 days from now
  {
    id: "apt-019",
    patient_id: "pat-9",
    patient: mockPatients[8],
    doctor_id: "doc-6",
    doctor: mockDoctors[5],
    specialty_id: "sp-2",
    specialty: mockSpecialties[1],
    appointment_type: "first_visit",
    status: "confirmed",
    scheduled_date: getRelativeDate(5),
    scheduled_start_time: "08:00",
    scheduled_end_time: "08:45",
    reason: "Chequeo general",
    created_at: getRelativeDate(-1),
  },
  {
    id: "apt-020",
    patient_id: "pat-10",
    patient: mockPatients[9],
    doctor_id: "doc-1",
    doctor: mockDoctors[0],
    specialty_id: "sp-1",
    specialty: mockSpecialties[0],
    appointment_type: "follow_up",
    status: "confirmed",
    scheduled_date: getRelativeDate(5),
    scheduled_start_time: "09:30",
    scheduled_end_time: "10:00",
    reason: "Revisión electrocardiograma",
    created_at: getRelativeDate(-2),
  },
];

export function useAppointments(filters?: AppointmentFilters) {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => setIsLoading(false), 300);
    return () => clearTimeout(timer);
  }, []);

  const data = useMemo(() => {
    if (!filters) return mockAppointments;

    return mockAppointments.filter((apt) => {
      if (filters.status !== "all" && apt.status !== filters.status)
        return false;
      if (filters.doctor_id !== "all" && apt.doctor_id !== filters.doctor_id)
        return false;
      if (
        filters.specialty_id !== "all" &&
        apt.specialty_id !== filters.specialty_id
      )
        return false;
      if (filters.date_from && apt.scheduled_date < filters.date_from)
        return false;
      if (filters.date_to && apt.scheduled_date > filters.date_to)
        return false;
      if (filters.search) {
        const q = filters.search.toLowerCase();
        const patientName =
          `${apt.patient?.first_name} ${apt.patient?.first_lastname}`.toLowerCase();
        const doctorName = apt.doctor?.full_name.toLowerCase() ?? "";
        if (!patientName.includes(q) && !doctorName.includes(q)) return false;
      }
      return true;
    });
  }, [filters]);

  return { data, isLoading };
}
